### ISSUE TITLE
Exception when there's not a matching record for a model in the database

### ISSUE THREAD

**Issue by Towanime** [yaroslawww/laravel-recently-viewed#1]
Using the package with the persist storage setting as true will throw an error if you try to fetch the recent views for a model that does not have any views yet.

The solution seems simple, adding a default array value [here:](https://github.com/yaroslawww/laravel-recently-viewed/blob/966600d57fcf62602cbf703f0b68d95a5a283496/src/RecentlyViewed.php#L51)

`$keys = session()->get(config('recently-viewed.session_prefix') . '.' . get_class($viewable));`

to

`$keys = session()->get(config('recently-viewed.session_prefix') . '.' . get_class($viewable), []);`

Putting more information in case I'm missing something else,

Stacktrace: 
> local.ALERT: TypeError: Argument 1 passed to Illuminate\Database\Query\Builder::cleanBindings() must be of the type array, null given, called in /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 919 and defined in /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3078
Stack trace:
#0 /vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(919): Illuminate\Database\Query\Builder->cleanBindings()
#1 /vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Query\Builder->whereIn()
#2 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1406): Illuminate\Database\Eloquent\Builder->forwardCallTo()
#3 /vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->__call()
#4 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1734): Illuminate\Database\Eloquent\Model->forwardCallTo()
#5 /vendor/yaroslawww/laravel-recently-viewed/src/Models/Traits/CanBeViewed.php(19): Illuminate\Database\Eloquent\Model->__call()
#6 /vendor/yaroslawww/laravel-recently-viewed/src/RecentlyViewed.php(53): App\Models\Model->whereRecentlyViewedIn()
#7 /vendor/yaroslawww/laravel-recently-viewed/src/RecentlyViewed.php(71): RecentlyViewed\RecentlyViewed->getQuery()
#8 /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): RecentlyViewed\RecentlyViewed->get()

**Comment by snipiba** [comment]
under RecentlyViewed.php after line 51, get check if $keys are null, or simply change whole line to this

```
$keys = session()->get(config('recently-viewed.session_prefix') . '.' . get_class($viewable)) ?? [];
```

>>> if session not exists (no views are stored for that class) simply return blank array
