### ISSUE TITLE
How to use persist storage

### ISSUE THREAD

**Issue by vlados** [yaroslawww/laravel-recently-viewed#11]
Where I need to put `\RecentlyViewed\PersistManager::enableMigrations()`?
Why not just use `php artisan vendor:publish --provider="RecentlyViewed\ServiceProvider" --tag="migrations"`

**Comment by yaroslawww** [comment]
You can enable migrations in any of your service providers, the `register` method.
If you want to change README doc, please create a pull request and I will approve it when I will have time.

----
Sorry I am not ready to change the migration flow to `publication` for now. Maybe in future versions.
