### ISSUE TITLE
Persist storage in separate database

### ISSUE THREAD

**Issue by dambridge** [yaroslawww/laravel-recently-viewed#15]
I have a different database where I want to keep the recently_viewed table. Is there a recommended way to do this? I cannot currently as I don't see anwhere where I can specify a different connection.

**Comment by yaroslawww** [comment]
Sorry for the delay.

You can try create your own model with custom connection and use it:

```php
PersistManager::useRecentlyViewedModel(MyModel::class);
```

[Here](https://github.com/laravel/framework/issues/29771) you can find chat that explains how to possible use different connection in relations
