### ISSUE TITLE
How do i use this in a blade view?

### ISSUE THREAD

**Issue by Rusteze** [yaroslawww/laravel-recently-viewed#3]
Hi, First of all thank for this awesome package. 

I don't think this is really an issue with your package but i just don't know exactly how to use this. I'm having trouble with the foreach loop. This is what i'm doing right now, but it doesn't always return the correct result. 

Can you tell me how to do this the right way?

```
@foreach(Session::get('recently_viewed')['App\Models\Product'] as $id)

<?php $product = $products->get($id); ?>

{{ $product->title }}
{{ $product->category->name }}
{{ $product->price }}

@endforeach
```

**Comment by yaroslawww** [comment]
Please check *README.md* file, there example:

```
$products = \RecentlyViewed\Facades\RecentlyViewed::get(Product::class);
// or
$products = \RecentlyViewed\Facades\RecentlyViewed::getQuery(Product::class)
            ->where('not_display_in_recently_list', false)->get();
```
and then:
```
@foreach($products as $product)
{{ $product->title }}
@endforeach
```
