### ISSUE TITLE
Update for PHP 8?

### ISSUE THREAD

**Issue by dambridge** [yaroslawww/laravel-recently-viewed#4]
Hi there, was hoping to check this out for a current app, but the PHP requirements don't line up. Just FYI. :)

**Comment by dambridge** [comment]
This installed: `composer require yaroslawww/laravel-recently-viewed --ignore-platform-req=php`

Now to see if it works!

**Comment by yaroslawww** [comment]
Added support in version 2.0. Thank you.
```
  "yaroslawww/laravel-recently-viewed": "^2.0",
```
