### ISSUE TITLE
Deletes from database when logging out

### ISSUE THREAD

**Issue by srijaydeathwish** [yaroslawww/laravel-recently-viewed#9]
Is there a way to keep the recently viewed even after logged out so that next time it is still there when logging back in?

**Comment by yaroslawww** [comment]
Data is stored only in the session and database. There is no any implementation with cookies. But after logging out the data should not be removed.

**Comment by srijaydeathwish** [comment]
> Data is stored only in the session and database. There is no any implementation with cookies. But after logging out the data should not be removed.

I followed every step, enabled persist as well and everything is working properly except everything gets cleared (even database entries) after logging out. I don't understand what I'm doing wrong. I followed your example.

**Comment by yaroslawww** [comment]
For version 3.0 - added tests what covers logout flow: https://github.com/yaroslawww/laravel-recently-viewed/blob/master/tests/MergePersistToCurrentSessionTest.php#L52

All tests pass, so maybe you reload session after logout (like `$request->session()->invalidate();`). In this case you need copy data to new session manually from previous session.
Also after end session lifetime (default 2h), session gone with all data.
